from playwright.sync_api import Page, expect
import time


def test_fill_out_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    time.sleep(3)
    page.get_by_placeholder('First Name').fill('Sergey')
    page.get_by_placeholder('Last Name').fill('Kostichev')
    page.get_by_placeholder('name@example.com').fill('sergey.kostichev@gmail.com')
    # page.get_by_role('button', name='Male').click()
    #page.locator('#gender-radio-1').click()
    #page.get_by_label('Male').click()
    #page.locator('input[name="gender"][value="Male"]').click()
    #page.locator('label.custom-control-label[for="gender-radio-1"]').click()
    #page.get_by_role('radio', name='Male').click()
    #page.locator('//input[@id="gender-radio-1"]').click()
    #page.locator('div.custom-control:has-text("Male") input[type="radio"]').click()
    page.get_by_placeholder('Mobile Number').fill('6666688998')
    page.locator('#dateOfBirthInput').fill('28 Feb 1989')
    page.locator('#subjectsInput').click()
    page.locator('#subjectsInput').fill('My Subject')
    #page.get_by_role('checkbox', name='Sports').click()
    #page.locator('#hobbies-checkbox-1').check()
    #page.get_by_label('Sports').click()
    page.get_by_placeholder('Current Address').fill('Home sweet home')
    state_field = page.locator('#state')
    state_field.click()
    state_field.press_sequentially('ncr')
    state_field.press('Enter')
    time.sleep(1)
    city_field = page.locator('#city')
    city_field.click()
    city_field.press_sequentially("Delhi")
    city_field.press('Enter')

    time.sleep(20)
    #page.locator('#city input[type="text"]').click()
    #page.locator('#city input[type="text"]').fill("Delhi")
    '''time.sleep(2)
    page.get_by_role('button', name='Submit').click()
    time.sleep(4)'''
